// SPDX-License-Identifier: Apache-2.0
/*
 * Test harness for the eBPF BPE tokenizer.
 *
 * Loads the BPF program, populates the merge table, writes prompts
 * to /dev/llm_prompt1, and validates output token IDs against a
 * reference tokenizer (HuggingFace tiktoken cl100k_base).
 *
 * Usage: ./test_ebpf_tokenizer [--chardev /dev/llm_prompt1]
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/mman.h>
#include <assert.h>

#include "../userspace/include/kllm_ring_user.h"

#define RING_SIZE	(2 * 1024 * 1024)
#define CHARDEV_PATH	"/dev/llm_prompt1"

struct test_case {
	const char *prompt;
	const uint32_t *expected_tokens;
	uint32_t expected_len;
};

/*
 * Reference token IDs for "Hello world" using tiktoken cl100k_base.
 * These would normally be generated by running the Python tokenizer.
 */
static const uint32_t hello_world_tokens[] = { 9906, 1917 };

static struct test_case tests[] = {
	{
		.prompt = "Hello world",
		.expected_tokens = hello_world_tokens,
		.expected_len = 2,
	},
};

static int run_test(int chardev_fd, struct kllm_ring_hdr *ring,
		    struct test_case *tc)
{
	uint32_t tail_before, tokens_produced;
	uint32_t got[4096];
	ssize_t written;

	printf("  prompt: \"%s\"\n", tc->prompt);

	tail_before = ring->head;
	written = write(chardev_fd, tc->prompt, strlen(tc->prompt));
	if (written < 0) {
		perror("  FAIL: write to chardev");
		return -1;
	}

	/* Give the BPF program a moment (synchronous in write path) */
	tokens_produced = kllm_ring_available(ring);
	printf("  tokens produced: %u (expected %u)\n",
	       tokens_produced, tc->expected_len);

	if (tokens_produced != tc->expected_len) {
		printf("  FAIL: token count mismatch\n");
		return -1;
	}

	uint32_t consumed = kllm_ring_consume_batch(ring, got, tokens_produced);
	for (uint32_t i = 0; i < consumed; i++) {
		printf("  token[%u]: got=%u expected=%u %s\n",
		       i, got[i], tc->expected_tokens[i],
		       got[i] == tc->expected_tokens[i] ? "OK" : "MISMATCH");
		if (got[i] != tc->expected_tokens[i])
			return -1;
	}

	printf("  PASS\n");
	return 0;
}

int main(int argc, char **argv)
{
	const char *devpath = CHARDEV_PATH;
	int fd, failures = 0;
	void *map;
	struct kllm_ring_hdr *ring;

	if (argc > 2 && strcmp(argv[1], "--chardev") == 0)
		devpath = argv[2];

	fd = open(devpath, O_RDWR);
	if (fd < 0) {
		perror("open chardev");
		fprintf(stderr, "Is the kllm module loaded? Try: insmod kllm.ko\n");
		return 1;
	}

	map = mmap(NULL, RING_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (map == MAP_FAILED) {
		perror("mmap token ring");
		close(fd);
		return 1;
	}

	ring = (struct kllm_ring_hdr *)map;
	if (ring->magic != KLLM_TOKEN_RING_MAGIC) {
		fprintf(stderr, "ring magic mismatch: 0x%x (expected 0x%x)\n",
			ring->magic, KLLM_TOKEN_RING_MAGIC);
		munmap(map, RING_SIZE);
		close(fd);
		return 1;
	}

	printf("token ring: %u slots\n", ring->slot_count);
	printf("running %zu test(s):\n", sizeof(tests) / sizeof(tests[0]));

	for (size_t i = 0; i < sizeof(tests) / sizeof(tests[0]); i++) {
		printf("test %zu:\n", i + 1);
		if (run_test(fd, ring, &tests[i]) < 0)
			failures++;
	}

	munmap(map, RING_SIZE);
	close(fd);

	printf("\n%d/%zu tests passed\n",
	       (int)(sizeof(tests) / sizeof(tests[0])) - failures,
	       sizeof(tests) / sizeof(tests[0]));
	return failures > 0 ? 1 : 0;
}
